HOST = "127.0.0.1"  
PORT = 5003 
MESSAGE_HEADER_START_DELIMITER= "***"
MESSAGE_KEYVAL_DELIMITER = ":"
MESSAGE_DATA_DELIMITER = ","
MESSAGE_HEADER_END_DELIMITER = "&&&"
MESSAGE_REQUEST_KEY = "request"
MESSAGE_DATA_TYPE_KEY = "data_type"
# wip: rework this with enums?
MESSAGE_SUPPORTED_DATA_TYPES = ["float_array", "int_array"]
SERVER_STATUS_ONLINE = "online"
SERVER_STATUS_ONLINE_WITH_CLIENT = "online_with_client"
SERVER_STATUS_OFFLINE = "offline"
SERVER_STATUSES = [SERVER_STATUS_ONLINE, SERVER_STATUS_ONLINE_WITH_CLIENT, SERVER_STATUS_OFFLINE]