HOST = "127.0.0.1"  
PORT = 5003 
MESSAGE_HEADER_START_DELIMITER= "***"
MESSAGE_KEYVAL_DELIMITER = ":"
MESSAGE_DATA_DELIMITER = ","
MESSAGE_HEADER_END_DELIMITER = "&&&"
MESSAGE_DATA_TYPE_KEY = "data_type"
MESSAGE_SUPPORTED_DATA_TYPES = ["float_array", "int_array"]