# Server

HOST = "127.0.0.1"  
PORT = 5002
MESSAGE_HEADER_START_DELIMITER= "***"
MESSAGE_KEYVAL_DELIMITER = ":"
MESSAGE_DATA_DELIMITER = "###"
MESSAGE_HEADER_END_DELIMITER = "&&&"
MESSAGE_ARR_DATA_DELIMITER = ","
MESSAGE_REQUEST_KEY = "request"
MESSAGE_DATA_TYPE_KEY = "data_type"
# wip: rework this with enums?
MESSAGE_SUPPORTED_DATA_TYPES = ["float_array", "int_array"]
SERVER_STATUS_ONLINE = "online"
SERVER_STATUS_ONLINE_WITH_CLIENT = "online_with_client"
SERVER_STATUS_OFFLINE = "offline"
SERVER_STATUSES = [SERVER_STATUS_ONLINE, SERVER_STATUS_ONLINE_WITH_CLIENT, SERVER_STATUS_OFFLINE]

# Gan
IMAGE_SHAPE = 256 # assuming it's a square
SLERP_STEPS = 4
GAN_WEIGHTS_PATH = "./data/gan/metfaces_G-e388.h5"
LATENT_VECTORS_PATH = "./data/gan/backend_latent_vectors_slices.csv"
LATENT_VECTORS_SKIP_HEADER = 1
SLE_GAN_VECTOR_SHAPE = (-1, 1, 1, IMAGE_SHAPE)